### ISSUE TITLE
Latest release doesn't provide Firefox addon (.xpi)

### ISSUE THREAD

**Issue by nirfse** [gabrielecirulli/hn-special#110]
Latest release (1.4.7) includes source code archives only. Please consider adding ready-to-use add-on (.xpi) for the Firefox browser.

**Comment by PxlBuzzard** [comment]
I've addressed this in another issue thread https://github.com/gabrielecirulli/hn-special/issues/33#issuecomment-239920928. I know it's been awhile, because the work needed to remove dependencies on innerHTML is frustrating. There is no obvious replacement for our small, well-scoped use of it from what I can find.

I'll count this thread as another vote for the short-term workaround (self-signed xpi) and close it for now. Thanks for taking the time to post, I appreciate hearing that others want to use the Firefox version too. :)
