### ISSUE TITLE
Firefox WebExtension support, using the Foxified Add-on 

### ISSUE THREAD

**Issue by dwolff** [gabrielecirulli/hn-special#117]
### Steps to reproduce this issue

1. Install Firefox Quantum
2. Install the [Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) addon (to allow Firefox to use Chrome extensions)
3. Install the [HN Special extension](https://chrome.google.com/webstore/detail/hn-special-an-addition-to/cchaceegbflphbdpfocjalgjhjoahiia)

### Expected result
Should work like it does in Chrome.

### Actual result
The page doesn't load. Looking further into the CSS, removing the "hnspecial-theme-preload" class from the html tag makes it behave like expected. The infinite scrolling still doesn't work, though.

**Comment by PxlBuzzard** [comment]
Huh, I didn't know about [Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) until this issue, thanks.

There's a couple issues that made this happen. First: back when I first added Firefox support in 2013, the browser did not have Web Extension support, so I needed to add a few "if Chrome, else Firefox" checks around the codebase. The way I did that was by checking for the existence of a global chrome object, which as it turns out became the default way to access browser functions for all Web Extensions. I've gone ahead and those browser checks.

The second issue specifically related to your "actual result" is that I had been relying on the "cascading" part of CSS to take care of showing the site once the page and extension have finished loading. Rather than let CSS have all the fun, it makes sense to use Javascript to remove the `hnspecial-theme-preload` class after the extension has loaded ([link to the change](/gabrielecirulli/hn-special/blob/master/lib/settings.js#L65)).

**Comment by PxlBuzzard** [comment]
I also fixed infinite scrolling in Firefox. For some reason Chrome will happily make requests to relative URLs, but Firefox wants the domain name in the request path. Adding the domain to the current page number fixed the problem. 12987eb0300f2c1b5d9bf222509dd9451dd5f9ba

**Comment by PxlBuzzard** [comment]
I published v1.4.9 to the Chrome Web Store, and I validated that it works in Firefox using Foxified. I also tried to resubmit to Firefox Addons, but they are still blocking on our usage of innerHTML (more info in https://github.com/gabrielecirulli/hn-special/issues/88)
