### ISSUE TITLE
Firefox Version?

### ISSUE THREAD

**Issue by aaronraimist** [gabrielecirulli/hn-special#33]
Would it be possible to port this to Firefox?

**Comment by PxlBuzzard** [comment]
Closed with the merge of #65

**Comment by FichteFoll** [comment]
Unfortunately, The .xpi files served on the releases page don't appear to be signed as firefox doesn't allow installation of those anymore.

**Comment by PxlBuzzard** [comment]
Ah ha, someone noticed! Let me list out the options and plan of attack:

1. Get a signing key so we can continue to release the Firefox addon via the Releases page.
2. Register the extension officially in Firefox Addons, which gives us an official release channel and auto-updates.

Clearly the latter option is the best option long-term. We've actually tried two submissions the last few months. The first review failed and resulted in issue #88. The second review failed for the same reason since we hadn't fixed the problem, but we thought it would be OK since the automated reviewer doesn't flag innerHTML as an error anymore and I wrote up a good justification for why our usage of it should be allowed.

I've spent a couple hours replacing our innerHTML usage throughout the addon, and I need to spend some more time making it all work without regressions. With Firefox v48 removing the ability to load unsigned addons, I have more incentive to get it done and try once again to get it into Firefox Addons.

If there is enough interest I can definitely go with the first option listed earlier and get a signed version released on Github as a short-term fix.

**Comment by PxlBuzzard** [comment]
I've gone ahead and submitted v1.4.8 to the Firefox Addons review team without all the innerHTML fixes, but a lot of justification text for why it should be allowed. If they deny it yet again from the Addons store, I will post a self-signed release here.
