### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by lebiru** [gabrielecirulli/hn-special#62]
see title

**Comment by benoror** [comment]
+1 for dark theme

**Comment by absorber** [comment]
+1 for dark theme. I don't understand why that [PR](https://github.com/gabrielecirulli/hn-special/pull/65) hasn't been merged yet.

**Comment by avyfain** [comment]
+1 This would be especially good for [f.lux](https://justgetflux.com/) users. It is really hard to read due to the low contrast against the tinted white background when f.lux is in bedtime mode.
<img width="1440" alt="screen shot 2016-05-15 at 11 46 35 pm" src="https://cloud.githubusercontent.com/assets/4804875/15282320/5cab94dc-1af7-11e6-86ef-aa74a08e7e7c.png">

**Comment by PxlBuzzard** [comment]
Closed with the merge of #65
